title: Harry's personal site
author: Harry Wang
email: harry2020@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for my new site.

# social links
twitter_username: IDontHaveAny
github_username:  harryustc

show_excerpts: true # set to false to remove excerpts on the homepage
